# defined variables
@HOST = localhost
@PORT = 8080
@API_URL = http://{{HOST}}:{{PORT}}/

#### home page------------------------------------
GET {{API_URL}}

####------------------------------------
GET {{API_URL}}v1/users/
####------------------------------------
POST {{API_URL}}v1/users/
####------------------------------------
PATCH {{API_URL}}v1/users/1
####------------------------------------
DELETE {{API_URL}}v1/users/1
