# defined variables
@HOST = localhost
@PORT = 8080
@API_URL = http://{{HOST}}:{{PORT}}/

#### home page------------------------------------
GET {{API_URL}}

####------------------------------------
GET {{API_URL}}v1/users/
####------------------------------------
POST {{API_URL}}v1/users/
####------------------------------------
PATCH {{API_URL}}v1/users/1
####------------------------------------
DELETE {{API_URL}}v1/users/1

####------------------------------------
GET {{API_URL}}v1/feed/abc

####------------------------------------
GET {{API_URL}}v1/feed/acd
####------------------------------------
GET {{API_URL}}v1/feed/abcd


####------------------------------------
GET {{API_URL}}v1/feed/barx
####------------------------------------
GET {{API_URL}}v1/feed/barrrrrrrx



####------------------------------------
GET {{API_URL}}v1/feed/fooabcx
####------------------------------------
GET {{API_URL}}v1/feed/foo123x



####------------------------------------

GET {{API_URL}}v1/feed/aaamy
####------------------------------------
GET {{API_URL}}v1/feed/123my
####------------------------------------
GET {{API_URL}}v1/feed/my123
####------------------------------------
GET {{API_URL}}v1/feed/123myabc



####------------------------------------
GET {{API_URL}}v1/feed/style
####------------------------------------
GET {{API_URL}}v1/feed/abc123_style